apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: event-display
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: event-display
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: event-display
  name: event-display
spec:
  containers:
  - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
    name: event-display
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
