apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: failing-sink
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: failing-sink
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: failing-sink
  name: failing-sink
spec:
  containers:
  - image: docker.io/aliok/failing-sink
    name: failing-sink
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
