apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-api-server-source-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-api-server-source-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-api-server-source-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-api-server-source-role
subjects:
  - kind: ServiceAccount
    name: test-api-server-source-sa
---
apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: test-api-server-source
spec:
  serviceAccountName: test-api-server-source-sa
  mode: "Resource"
  resources:
    - apiVersion: v1
      kind: Event
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
