apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: kafka-channel
spec:
  delivery:
    deadLetterSink:
      ref:
        apiVersion: v1
        kind: Service
        name: event-display
    # retry

