apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: kafka-channel
spec:
  numPartitions: 10
  replicationFactor: 3
  delivery:
    retry: 12
    backoffPolicy: exponential
    backoffDelay: PT1S

